version: '3'
services:
  graph-node:
    image: graphprotocol/graph-node
    container_name: graph-node
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8020:8020"
    depends_on:
      - ipfs
      - postgres
    environment:
      postgres_host: postgres
      postgres_user: kralus
      postgres_pass: ZBxMqnpB3wCSVNwC
      postgres_db: graph-node
      ipfs: "ipfs:5001"
      ethereum: "dev:http://parity:8545"
  ipfs:
    image: ipfs/go-ipfs
    container_name: ipfs
    ports:
      - "5001:5001"
    volumes:
      - ./data/ipfs:/data/ipfs
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: kralus
      POSTGRES_PASSWORD: ZBxMqnpB3wCSVNwC
      POSTGRES_DB: graph-node
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  parity:
    image: parity/parity
    container_name: parity
    ports:
      - "8545:8545"
      - "8546:8546"
      - "3030:3030"
    volumes:
      - ./parity:/home/parity/.local/share/io.parity.ethereum/
    command: >
      --config /home/parity/.local/share/io.parity.ethereum/config.toml
      --base-path /home/parity/.local/share/io.parity.ethereum
